# Generated by Django 6.0.4 on 2026-04-24

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    Field = apps.get_model('core', 'Field')
    for field in Field.objects.filter(public_id__isnull=True):
        field.public_id = uuid.uuid4()
        field.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='field',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
